# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d5f2422083931bd896fb688a132e05900254e2e2985014671007208dc3cf20b6e061c988fc15ddd1ffc5f25da2f46f437e527808269e07991d8d94720a3dd9

test:
  secret_key_base: 391b5d6e9935601c0c995ed8e46a67e0fe4757a10cd3f33355579f63577a79f0246c0e73bd93a76236b2ae1382b601c09eebf1d964891eb8f491df8899f9b690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
